name: Update PR Description with Dynamic Values

permissions:
  pull-requests: write

on:
  pull_request:
    types: [ opened ]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Update PR Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          REPO=${{ github.repository }}

          CURRENT_DESCRIPTION="${{ github.event.pull_request.body }}"

          UPDATED_DESCRIPTION=$(echo "$CURRENT_DESCRIPTION" |
            sed "s/{{PR_NUMBER}}/$PR_NUMBER/g" |
            sed "s/{{BRANCH_NAME}}/$BRANCH_NAME/g"
          )

          curl -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER \
            -d '{"body":\"$UPDATED_DESCRIPTION\"}'
